driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-7.3
  - name: debian-8.8
  - name: debian-9.0
  - name: ubuntu-16.04

suites:
  - name: docker-master
    run_list:
      - recipe[kubernetes::master]
  - name: decker-worker
    run_list:
      - recipe[kubernetes::node]
