#<% require 'kitchen-sync' %>
---
driver_config:
   digitalocean_access_token: <%= ENV['DIGITALOCEAN_API_TOKEN'] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: true

verifier:
  name: inspec

platforms:
- name: centos-7.0
  driver_plugin: digitalocean
  driver_config:
    size: 2gb
    image: centos-7-0-x64
    region: <%= ENV['DIGITALOCEAN_REGION'] %>
    ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEYS'] %>
  transport:
    ssh_key: <%= ENV['DIGITALOCEAN_SSH_KEY_PATH'] %>
  run_list:
  - recipe[yum-docker]

suites:
  # - name: default
  #   run_list:
  #     - recipe[k8s::default]
  #     - recipe[k8s::master]
  #     - recipe[k8s::node]
  #   attributes:
  # - name: docker
  #   run_list:
  #     - recipe[k8s::docker_install]
  #   attributes:
  - name: decker-master
    run_list:
      - recipe[kubernetes::master]
    attributes:
      kubernetes:
        client_version: '0.3.0'
  - name: decker-worker
    run_list:
      - recipe[kubernetes::node]
    attributes:
      kubernetes:
        client_version: '0.3.0'
  - name: decker-worker-2
    run_list:
      - recipe[kubernetes::node]
    attributes:
      kubernetes:
        client_version: '0.3.0'
#  - name: node-1
#    run_list:
#      - recipe[k8s::default]
#      - recipe[k8s::node]
#    attributes:
